server:
  port: 8080
  servlet:
    context-path: /identity

##Swagger api
open:
  api:
    title: API document
    version: v1.0.0
    description: API service
    serverUrl: http://localhost:8080
    serverName: server test

spring:
  ##Database
  datasource:
    url: "jdbc:mysql://localhost:3306/identity"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


##JWT token
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 #in second
  refreshable-duration: 36000 #in second

## Cloudinary
cloudinary:
  cloud_name: "dkxwnkii4"
  api_key: "122237874773556"
  api_secret: "GHD93O9ICu6_e3AP3Mp1IvEP_Lk"
